ALTER TABLE revision.questions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE revision.questions ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE revision.notes ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE revision.notes ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
